services:
  postgres:
    image: postgres:16
    container_name: transcendence_postgres
    restart: always
    environment:
      POSTGRES_USER: transcendence
      POSTGRES_PASSWORD_FILE: /run/secrets/postgres_password
      POSTGRES_DB: transcendence_db
    networks:
      - transcendence
    volumes:
      - postgres_data:/var/lib/postgresql/data
    secrets:
      - postgres_password
    ports:
      - "5432:5432"

  # app:
  #   build: .
  #   container_name: trans_backend
  #   restart: always
  #   ports:
  #     - "3000:3000"
  #   depends_on:
  #     - postgres
  #   env_file:
  #     - .env
  #   volumes:
  #     - .:/app
  #   command: npm run start:migrate:prod
  #   networks:
  #     - transcendence
      
networks:
  transcendence:
    
secrets:
  postgres_password:
    file: ./secrets/postgres_password
volumes:
  postgres_data: